package heimdall.common.enums;

public enum EDomainEvents {
  CONTROLLER_CREATE_USER,
  CONTROLLER_CREATE_APP,
  CONTROLLER_UPSERT_ACTIVITY,
  COMMAND_CREATE_USER,
  COMMAND_CREATE_APP,
  COMMAND_UPSERT_ACTIVITY,
}
